language: android

sudo: false

jdk:
  - oraclejdk7

android:
  components:
    - platform-tools
    - tools
    - android-23
    - build-tools-23.0.3
    - extra-google-m2repository
    - extra-android-m2repository

script: ./gradlew build check --stacktrace

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e462044d3105a7bb4b4f
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
