language: android

jdk:
 - oraclejdk8

env:
  - TERM=dumb

android:
  components:
    - tools
    - build-tools-23.0.3
    - android-23

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
script:
  - ./gradlew build
deploy:
  provider: releases
  api_key: $GITHUB_ACCESS_TOKEN
  file:
    - build/outputs/apk/talalarmo-debug.apk
  skip_cleanup: true
  on:
    tags: true
